function mkcd() { mkdir -p $1; cd $1;}
alias cp='cp -riv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias v='nvim'
alias l='exa --sort=changed -la -G'
alias la='exa --group-directories-first -la'
alias ll='exa --group-directories-first -la --color-scale --time-style=long-iso -T -L2'
alias ll3='exa --group-directories-first -la -T -L3'
alias ll4='exa --group-directories-first -la -T -L4'
alias tree='exa --group-directories-first -T'
alias c='clear'
alias gd='git diff'
alias ga='git add'
alias gs='git status'
alias gc='git commit'
alias gb='git branch'
alias gp='git push'
alias t='tmux attach -t $(tmux list-sessions -F "#{session_name}" | fzf) || tmux new-session'
